name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      PORT: 3003
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      SECRET: ${{ secrets.SECRET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install && cd client && npm install
      - name: Check style
        run: npm run lint
      - name: Build
        run: npm run build
      - name: test Backend
        run: npm run testBE
      - name: test Frontend
        run: npm run testFE
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3003
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "blog-list-mh"
          heroku_email: "mira.m.hamalainen@gmail.com"
          branch: "main"
          healthcheck: "https://blog-list-mh-9c2ec62b82de.herokuapp.com/health"
          checkstring: "ok"
          delay: 10
          rollbackonhealthcheckfailed: true